###
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MTJlZWQ4LWFlYjItNDhkMS05OGNlLTEyZWRmODU3NjA3ZiIsImlhdCI6MTY1NjAyNTA4OCwiZXhwIjoxNjU2MDQzMDg4fQ.gjUT6kXyauVoMmQFvr5yJJi0WaTZzXcG8CMYMogiwRY

###
GET http://localhost:3003/user/d512eed8-aeb2-48d1-98ce-12edf857607f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MTJlZWQ4LWFlYjItNDhkMS05OGNlLTEyZWRmODU3NjA3ZiIsImlhdCI6MTY1NjAyNTA4OCwiZXhwIjoxNjU2MDQzMDg4fQ.gjUT6kXyauVoMmQFvr5yJJi0WaTZzXcG8CMYMogiwRY

###
GET http://localhost:3003/recipe/f03542d2-f8c0-4f11-aeb0-e250b45159bc
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MTJlZWQ4LWFlYjItNDhkMS05OGNlLTEyZWRmODU3NjA3ZiIsImlhdCI6MTY1NjAyNTA4OCwiZXhwIjoxNjU2MDQzMDg4fQ.gjUT6kXyauVoMmQFvr5yJJi0WaTZzXcG8CMYMogiwRY

### 
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"Malu",
    "email": "Malu@email.com", 
    "password": "gol@2015"
}

### 
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MTJlZWQ4LWFlYjItNDhkMS05OGNlLTEyZWRmODU3NjA3ZiIsImlhdCI6MTY1NjAyNzYzNSwiZXhwIjoxNjU2MDQ1NjM1fQ.6DNs4D9-Lgs_9-iWA9NvMQlTzStNvTz35xatmuWH68A

{
    "title":"Massa Fresca",
    "description": "Misture ovos e farinha até dar liga, depois abra a massa e corte em tiras finas."
}

### 
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "Danie@email.com", 
    "password": "gol@2015"
}